name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fms-angular-app 
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install
        working-directory:  ./fms-angular-app 
        
      - name: Build Angular
        run: npm run build --configuration development --base-href ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fms-angular-app/dist/fms-angular-app/browser
      - name: List files
        run: ls ./dist/fms-angular-app/browser
